name: Build and Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Restore dependencies
        run: dotnet restore XmlGoamlSolution.sln

      - name: Build
        run: dotnet build XmlGoamlSolution.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test XmlGoamlSolution.sln --configuration Release --no-build --verbosity normal

      - name: Publish NuGet package
        run: dotnet pack XmlGoamlSolution.sln --configuration Release --no-restore --output ./artifacts
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Push NuGet package
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
